# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Float's Blog
subtitle: "Two people's blog"
description: 随便写点什么
keywords:
  - 笔记
  - 技术
author: aveandar
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://floatstream.vercel.app
root: /
permalink: post/:name/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
# external_link: true # Open external links in new tab
external_link:
  enable: true
  field: site
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly
plugin:
  - hexo-generator-feed
  - hexo-generator-sitemap
  - hexo-filter-nofollow

# include/exclude/ignore
exclude:
  - images

# rss
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: #icon.png
  autodiscovery: true
  template:

# sitemap
sitemap:
  path:
    - sitemap.xml
    - sitemap.txt
  tags: true
  categories: true
  rel: true

# nofollow
nofollow:
  enable: true
  field: site
  exclude:

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:FloatStream/FloatStream.github.io.git
  branch: master

#markdown-it
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-deflist
    - markdown-it-emoji
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-mark
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-cjk-breaks
    - markdown-it-checkbox
    #- name: 'markdown-it-task-checkbox'
    - name: '@neilsustc/markdown-it-katex'
      options:
        strict: false
  anchors:
    level: 1
    collisionSuffix: 'x'
    permalink: true
    permalinkClass: 'header-anchor'
    permalinkSide: 'right'
    permalinkSymbol: '¶'
    case: 0
    separator: '-'
